# Uvod v NumPy


## Understanding Data Types in Python



```C
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```


```python
# Python code
result = 0
for i in range(100):
    result += i
```


In [1]:
# Python code
x = 4
x = "four"



```C
/* C code */
int x = 4;
x = "four";  // FAILS
```


### A Python Integer Is More Than Just an Integer



```C
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```


<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/cint_vs_pyint.png" alt="Integer Memory Layout">

### A Python List Is More Than Just a List




In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [4]:
L2 = [str(c) for c in L]

In [5]:
type(L2[0])

str

In [6]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]


<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png" alt="Array Memory Layout">

### Fixed-Type Arrays in Python



In [ ]:
import array

L = list(range(10))
A = array.array('i', L)
A

## Example: Data analysis in pure Python

In [7]:
import csv

dataset_path = "data/f500_small.csv"

with open(dataset_path, "r") as f:
    f500_small = list(csv.reader(f))

In [9]:
print(f500_small[:3])

[['company', 'rank', 'revenues', 'revenue_change', 'profits', 'assets', 'profit_change', 'ceo', 'industry', 'sector', 'previous_rank', 'country', 'hq_location', 'website', 'years_on_global_500_list', 'employees', 'total_stockholder_equity'], ['Walmart', '1', '485873', '0.8', '13643.0', '198825', '-7.2', 'C. Douglas McMillon', 'General Merchandisers', 'Retailing', '1', 'USA', 'Bentonville, AR', 'http://www.walmart.com', '23', '2300000', '77798'], ['State Grid', '2', '315199', '-4.4', '9571.3', '489838', '-6.2', 'Kou Wei', 'Utilities', 'Energy', '2', 'China', 'Beijing, China', 'http://www.sgcc.com.cn', '17', '926067', '209456']]


In [10]:
len(f500_small)

20

In [18]:
total_revenues = sum([int(row[2]) for row in f500_small[1:]])

In [19]:
total_revenues

4305395

## How Vectorization Makes Code Faster



<p><img alt="Translating Python code to bytecode" src="https://s3.amazonaws.com/dq-content/289/bytecode.svg"></p>


<table>
<thead>
<tr>
<th>Language Type</th>
<th>Example</th>
<th>Time taken to write program</th>
<th>Control over program performance</th>
</tr>
</thead>
<tbody>
<tr>
<td>High-Level</td>
<td>Python</td>
<td>Low</td>
<td>Low</td>
</tr>
<tr>
<td>Low-Level</td>
<td>C</td>
<td>High</td>
<td>High</td>
</tr>
</tbody>
</table>



<p><img alt="For loop to sum rows" src="https://s3.amazonaws.com/dq-content/289/for_loop.svg"></p>

In [20]:
my_numbers = [[6,5], [1,3], [5,6]]

sums = []

for row in my_numbers:
    row_sum = row[0] + row[1]
    sums.append(row_sum)
    
print(sums)    

[11, 4, 11]


<p><img src="./images/numpy_for.gif"></p>

<p><img src="./images/numpy_vectorized.gif"></p>

Primerjeva hitrosti:

In [21]:
import numpy as np
size = 5_000_000

# Python - declaring lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Numpy - declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

In [22]:
print(list1[:5])
print(array1[:5])

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [23]:
%%timeit -n 3 -r 1

sums = []

for el1, el2 in zip(list1, list2):
    row_sum = el1 + el2
    sums.append(row_sum)

print(sums[:5])

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
1.33 s ± 0 ns per loop (mean ± std. dev. of 1 run, 3 loops each)


In [24]:
%%timeit -n 10 -r 1

sums = array1 + array2

48.9 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)


## Numpy library

[Dokumentacija](http://www.numpy.org/)

In [25]:
import numpy as np 

In [26]:
np.__version__

'1.23.4'

## Introduction to Ndarrays

<img alt="Dimensional Arrays" src="./images/one_dim.svg">

In [27]:
data_ndarray = np.array([5, 10, 15, 20])

In [29]:
print(data_ndarray)

[ 5 10 15 20]


In [30]:
#preverimo kakšen tip je spremenljivka
print(type(data_ndarray)) 

<class 'numpy.ndarray'>


<img alt="Dimensional Arrays" src="./images/Two_Dim.svg">

In [31]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


## Reading CSV files with NumPy

Below is information about selected columns from the data set:
- `rank`
- `revenue`
- `revenue_change`
- `profits`
- `asset`
- `profit_change`




    np.genfromtxt(filename, delimiter=None)

- `filename`: A positional argument, usually a string representing the path to the text file to be read.
- `delimiter`: A named argument, specifying the string used to separate each value.
- `usecols`: Which columns to read, with 0 being the first. For example, usecols = (1, 4, 5) will extract the 2nd, 5th and 6th columns.



    data = np.genfromtxt('data.csv', delimiter=',')

In [40]:
f500 = np.genfromtxt("data/f500_small.csv", delimiter=",", skip_header=1, usecols=tuple(range(1,7)))

In [41]:
f500[:5]

array([[ 1.00000e+00,  4.85873e+05,  8.00000e-01,  1.36430e+04,
         1.98825e+05, -7.20000e+00],
       [ 2.00000e+00,  3.15199e+05, -4.40000e+00,  9.57130e+03,
         4.89838e+05, -6.20000e+00],
       [ 3.00000e+00,  2.67518e+05, -9.10000e+00,  1.25790e+03,
         3.10726e+05, -6.50000e+01],
       [ 4.00000e+00,  2.62573e+05, -1.23000e+01,  1.86750e+03,
         5.85619e+05, -7.37000e+01],
       [ 5.00000e+00,  2.54694e+05,  7.70000e+00,  1.68993e+04,
         4.37575e+05, -1.23000e+01]])

In [43]:
f500.shape

(19, 6)

In [44]:
f500.dtype

dtype('float64')

In [45]:
f500[:7]

array([[ 1.00000e+00,  4.85873e+05,  8.00000e-01,  1.36430e+04,
         1.98825e+05, -7.20000e+00],
       [ 2.00000e+00,  3.15199e+05, -4.40000e+00,  9.57130e+03,
         4.89838e+05, -6.20000e+00],
       [ 3.00000e+00,  2.67518e+05, -9.10000e+00,  1.25790e+03,
         3.10726e+05, -6.50000e+01],
       [ 4.00000e+00,  2.62573e+05, -1.23000e+01,  1.86750e+03,
         5.85619e+05, -7.37000e+01],
       [ 5.00000e+00,  2.54694e+05,  7.70000e+00,  1.68993e+04,
         4.37575e+05, -1.23000e+01],
       [ 6.00000e+00,  2.40264e+05,  1.50000e+00,  5.93730e+03,
         4.32116e+05,          nan],
       [ 7.00000e+00,  2.40033e+05, -1.18000e+01,  4.57500e+03,
         4.11275e+05,  1.35900e+02]])

## Array Shapes

In [59]:
data_ndarray = np.array([[5, 10, 15], 
                         [20, 25, 30]])

In [60]:
data_ndarray

array([[ 5, 10, 15],
       [20, 25, 30]])

In [61]:
#the total number of elements of the array.
print(data_ndarray.size)

6


In [62]:
#the number of axes (dimensions) of the array.
print(data_ndarray.ndim)

2


In [64]:
# the size in bytes of each element of the array
print(data_ndarray.itemsize)

8


In [65]:
print(data_ndarray.nbytes)

48


In [66]:
# an object describing the type of the elements in the array. 
# One can create or specify dtype’s using standard Python types. 
# Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
print(data_ndarray.dtype)

int64


<div class="alert alert-block alert-info">
<b>Vaja:</b> Preverite še vse lastnosti za f500 array.</div>

In [67]:
print(f500.dtype)
print(f500.size)
print(f500.itemsize)
print(f500.ndim)
print(f500.nbytes)

float64
114
8
2
912


## Selecting and Slicing Rows and Items from ndarrays

<img alt="Dimensional Arrays" src="./images/selection_rows.svg">

    ndarray[row_index,column_index]

    # or if you want to select all
    # columns for a given set of rows
    ndarray[row_index]

<img alt="Dimensional Arrays" src="./images/selection_item.svg">

In [95]:
# Create a 5x5 array of random integrs in the interval [0, 10)
np.random.seed(0)
test = np.random.randint(0, 10, (5, 5))

In [96]:
test

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [97]:
test[0]

array([5, 0, 3, 3, 7])

In [98]:
test[-1]

array([5, 9, 8, 9, 4])

In [99]:
test[1:3]

array([[9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [100]:
test[2:]

array([[7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [101]:
test[:2]

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4]])

In [102]:
test[2,1]

6

<div class="alert alert-block alert-info">
<b>Vaja:</b> Izberite vrednost in vrstico f500 array-ja.</div>

## Selecting Columns and Custom Slicing ndarrays

<img alt="Dimensional Arrays" src="./images/selection_columns_updated.svg">

<img alt="Dimensional Arrays" src="./images/selection_1darray_updated.svg">

<img alt="Dimensional Arrays" src="./images/selection_2darray_updated.svg">

In [109]:
# Create an array filled with random values
columns_test = np.random.randint(1,10,(5,5))

In [110]:
columns_test

array([[2, 8, 4, 7, 8],
       [3, 1, 4, 6, 5],
       [5, 7, 5, 5, 4],
       [5, 5, 9, 5, 4],
       [8, 6, 6, 1, 2]])

In [111]:
columns_test[:,3]

array([7, 6, 5, 5, 1])

In [112]:
columns_test[:,1:3]

array([[8, 4],
       [1, 4],
       [7, 5],
       [5, 9],
       [6, 6]])

In [113]:
columns_test[2, 2:]

array([5, 5, 4])

In [114]:
columns_test[3:, 1:]

array([[5, 9, 5, 4],
       [6, 6, 1, 2]])

## Vector Math

In [115]:
my_numbers = [[6,5], [9,1], [2,4], [7,14], [8,6]]

In [116]:
my_numbers

[[6, 5], [9, 1], [2, 4], [7, 14], [8, 6]]

In [117]:
sums = []
for row in my_numbers:
    row_sums = row[0] + row[1]
    sums.append(row_sums)
    
print(sums)

[11, 10, 6, 21, 14]


In [119]:
# convert the list of lists to an ndarray
my_numbers = np.array(my_numbers)

In [120]:
my_numbers

array([[ 6,  5],
       [ 9,  1],
       [ 2,  4],
       [ 7, 14],
       [ 8,  6]])

In [121]:
col1 = my_numbers[:,0]

In [122]:
col1

array([6, 9, 2, 7, 8])

In [124]:
col2 = my_numbers[:,1]

In [125]:
col2

array([ 5,  1,  4, 14,  6])

In [130]:
col1 + col2

array([11, 10,  6, 21, 14])

In [132]:
sums = my_numbers[:,0] + my_numbers[:,1]

In [133]:
sums

array([11, 10,  6, 21, 14])

In [135]:
my_numbers.T

array([[ 6,  9,  2,  7,  8],
       [ 5,  1,  4, 14,  6]])

<div class="alert alert-block alert-info">
<b>Vaja:</b> 
Use vector addition to add revenues (1) and profits (3). Assign the result to revenues_and_profits.</div>

In [136]:
revenues = f500[:,1]
profits = f500[:,3]
revenues_and_profits = revenues + profits
revenues_and_profits

array([499516. , 324770.3, 268775.9, 264440.5, 271593.3, 246201.3,
       244608. , 247678. , 261326. , 212844. , 203603. , 186721. ,
       191857. , 182843. , 193273.5, 175262. , 178911.4, 175807. ,
       176762. ])



<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>The following table lists the arithmetic operators implemented in NumPy:</p>
<table>
<thead><tr>
<th>Operator</th>
<th>Equivalent ufunc</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>+</code></td>
<td><code>np.add</code></td>
<td>Addition (e.g., <code>1 + 1 = 2</code>)</td>
</tr>
<tr>
<td><code>-</code></td>
<td><code>np.subtract</code></td>
<td>Subtraction (e.g., <code>3 - 2 = 1</code>)</td>
</tr>
<tr>
<td><code>-</code></td>
<td><code>np.negative</code></td>
<td>Unary negation (e.g., <code>-2</code>)</td>
</tr>
<tr>
<td><code>*</code></td>
<td><code>np.multiply</code></td>
<td>Multiplication (e.g., <code>2 * 3 = 6</code>)</td>
</tr>
<tr>
<td><code>/</code></td>
<td><code>np.divide</code></td>
<td>Division (e.g., <code>3 / 2 = 1.5</code>)</td>
</tr>
<tr>
<td><code>//</code></td>
<td><code>np.floor_divide</code></td>
<td>Floor division (e.g., <code>3 // 2 = 1</code>)</td>
</tr>
<tr>
<td><code>**</code></td>
<td><code>np.power</code></td>
<td>Exponentiation (e.g., <code>2 ** 3 = 8</code>)</td>
</tr>
<tr>
<td><code>%</code></td>
<td><code>np.mod</code></td>
<td>Modulus/remainder (e.g., <code>9 % 4 = 1</code>)</td>
</tr>
</tbody>
</table>

</div>
</div>


In [139]:
np.add(col1, col2)

array([11, 10,  6, 21, 14])

In [141]:
# skalarno množenje
np.dot(col1, col2)

193

## Calculating Statistics For 1D ndarrays

In [142]:
profits = f500[:,3]

In [143]:
profits.max()

45687.0

In [144]:
np.max(profits)

45687.0

<div class="alert alert-block alert-info">
<b>Vaja:</b> Use the ndarray.min() method to calculate the minimum value of revenues. Assign the result to revenues_min.
Use the ndarray.mean() method to calculate the average value of profits. Assign the result to profits_mean.</div>

In [145]:
profits.mean()

10599.905263157894

<div>

<table>
<thead>
<tr>
<th>Calculation</th>
<th>Function Representation</th>
<th>Method Representation</th>
</tr>
</thead>
<tbody>
<tr>
<td>Calculate the minimum value of <code>trip_mph</code></td>
<td><code>np.min(trip_mph)</code></td>
<td><code>trip_mph.min()</code></td>
</tr>
<tr>
<td>Calculate the maximum value of <code>trip_mph</code></td>
<td><code>np.max(trip_mph)</code></td>
<td><code>trip_mph.max()</code></td>
</tr>
<tr>
<td>Calculate the <a target="_blank" href="https://en.wikipedia.org/wiki/Mean">mean average</a> value of <code>trip_mph</code></td>
<td><code>np.mean(trip_mph)</code></td>
<td><code>trip_mph.mean()</code></td>
</tr>
<tr>
<td>Calculate the <a target="_blank" href="https://en.wikipedia.org/wiki/Median">median average</a> value of <code>trip_mph</code></td>
<td><code>np.median(trip_mph)</code></td>
<td>There is no ndarray median method</td>
</tr>
</tbody>
</table>
</div>

## Calculating Statistics For 2D ndarrays

<img alt="Dimensional Arrays" src="./images/array_method_axis_none.svg">

<img alt="Dimensional Arrays" src="./images/array_method_axis_1.svg">

<img alt="Dimensional Arrays" src="./images/array_method_axis_0.svg">



<p><img alt="The axis parameter" src="https://s3.amazonaws.com/dq-content/289/axis_param.svg"></p>


In [146]:
f500.mean(axis=0)

array([ 1.00000000e+01,  2.26599737e+05, -1.94736842e-01,  1.05999053e+04,
        3.10729579e+05,             nan])

## Datatypes

In [147]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"
print(x.nbytes)

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)
print(x.nbytes)

int64
16
float64
16


In [148]:
x = np.array([1, 2], dtype=np.int32)   # Force a particular datatype
print(x.dtype)                         # Prints "int32"
print(x.nbytes)

x = np.array([1, 2], dtype=np.int8)   # Force a particular datatype
print(x.dtype)                         # Prints "int32"
print(x.nbytes)

int32
8
int8
2


<div class="text_cell_render border-box-sizing rendered_html">
<table>
<thead><tr>
<th>Data type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>bool_</code></td>
<td>Boolean (True or False) stored as a byte</td>
</tr>
<tr>
<td><code>int_</code></td>
<td>Default integer type (same as C <code>long</code>; normally either <code>int64</code> or <code>int32</code>)</td>
</tr>
<tr>
<td><code>intc</code></td>
<td>Identical to C <code>int</code> (normally <code>int32</code> or <code>int64</code>)</td>
</tr>
<tr>
<td><code>intp</code></td>
<td>Integer used for indexing (same as C <code>ssize_t</code>; normally either <code>int32</code> or <code>int64</code>)</td>
</tr>
<tr>
<td><code>int8</code></td>
<td>Byte (-128 to 127)</td>
</tr>
<tr>
<td><code>int16</code></td>
<td>Integer (-32768 to 32767)</td>
</tr>
<tr>
<td><code>int32</code></td>
<td>Integer (-2147483648 to 2147483647)</td>
</tr>
<tr>
<td><code>int64</code></td>
<td>Integer (-9223372036854775808 to 9223372036854775807)</td>
</tr>
<tr>
<td><code>uint8</code></td>
<td>Unsigned integer (0 to 255)</td>
</tr>
<tr>
<td><code>uint16</code></td>
<td>Unsigned integer (0 to 65535)</td>
</tr>
<tr>
<td><code>uint32</code></td>
<td>Unsigned integer (0 to 4294967295)</td>
</tr>
<tr>
<td><code>uint64</code></td>
<td>Unsigned integer (0 to 18446744073709551615)</td>
</tr>
<tr>
<td><code>float_</code></td>
<td>Shorthand for <code>float64</code>.</td>
</tr>
<tr>
<td><code>float16</code></td>
<td>Half precision float: sign bit, 5 bits exponent, 10 bits mantissa</td>
</tr>
<tr>
<td><code>float32</code></td>
<td>Single precision float: sign bit, 8 bits exponent, 23 bits mantissa</td>
</tr>
<tr>
<td><code>float64</code></td>
<td>Double precision float: sign bit, 11 bits exponent, 52 bits mantissa</td>
</tr>
<tr>
<td><code>complex_</code></td>
<td>Shorthand for <code>complex128</code>.</td>
</tr>
<tr>
<td><code>complex64</code></td>
<td>Complex number, represented by two 32-bit floats</td>
</tr>
<tr>
<td><code>complex128</code></td>
<td>Complex number, represented by two 64-bit floats</td>
</tr>
</tbody>
</table>

</div>

In [149]:
np.array([200, 22, 0, -129], dtype="int8")

array([-56,  22,   0, 127], dtype=int8)

## Boolean Indexing

### Boolean Arrays

In [ ]:
print(type(3.5) == float)

In [ ]:
print(5 > 6)

In [ ]:
print(np.array([2,4,6,8]) + 10)

<div class="alert alert-block alert-info">
Use vectorized boolean operations to:
<li> Evaluate whether the elements in array a are less than 3. Assign the result to a_bool.</li> 
<li> Evaluate whether the elements in array b are equal to "blue". Assign the result to b_bool.</li> 
<li>  Evaluate whether the elements in array c are greater than 100. Assign the result to c_bool.</li> </div>

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])

### Boolean Indexing with 1D ndarrays

In [ ]:
c = np.array([80.0, 103.4, 6.9, 200.3])


<div class="alert alert-block alert-info">Izračunamo nekaj statistik za f500 podatke.</div>

### Boolean Indexing with 2D ndarrays

<img alt="Dimensional Arrays" src="./images/bool_dims_updated.svg">

## The meaning of shapes in NumPy

**1-DIMENSIONAL NUMPY ARRAYS ONLY HAVE ONE AXIS**

**2-DIMENSIONAL NUMPY ARRAYS**

In [ ]:
a = np.arange(12)
print(a)

<pre class="lang-py s-code-block"><code class="hljs language-python">┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
│  <span class="hljs-number">0</span> │  <span class="hljs-number">1</span> │  <span class="hljs-number">2</span> │  <span class="hljs-number">3</span> │  <span class="hljs-number">4</span> │  <span class="hljs-number">5</span> │  <span class="hljs-number">6</span> │  <span class="hljs-number">7</span> │  <span class="hljs-number">8</span> │  <span class="hljs-number">9</span> │ <span class="hljs-number">10</span> │ <span class="hljs-number">11</span> │
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
</code></pre>

In [ ]:
a.shape

In [ ]:
# lokacija podatkov v pomnilniku
a.__array_interface__['data']

<pre class="lang-py s-code-block"><code class="hljs language-python">i= <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>    <span class="hljs-number">4</span>    <span class="hljs-number">5</span>    <span class="hljs-number">6</span>    <span class="hljs-number">7</span>    <span class="hljs-number">8</span>    <span class="hljs-number">9</span>   <span class="hljs-number">10</span>   <span class="hljs-number">11</span>
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
│  <span class="hljs-number">0</span> │  <span class="hljs-number">1</span> │  <span class="hljs-number">2</span> │  <span class="hljs-number">3</span> │  <span class="hljs-number">4</span> │  <span class="hljs-number">5</span> │  <span class="hljs-number">6</span> │  <span class="hljs-number">7</span> │  <span class="hljs-number">8</span> │  <span class="hljs-number">9</span> │ <span class="hljs-number">10</span> │ <span class="hljs-number">11</span> │
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
</code></pre>

In [ ]:
a[2]

In [ ]:
b.shape

In [ ]:
b.__array_interface__['data']

<pre class="lang-py s-code-block"><code class="hljs language-python">i= <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">1</span>    <span class="hljs-number">1</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">2</span>    <span class="hljs-number">2</span>    <span class="hljs-number">2</span>
j= <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
│  <span class="hljs-number">0</span> │  <span class="hljs-number">1</span> │  <span class="hljs-number">2</span> │  <span class="hljs-number">3</span> │  <span class="hljs-number">4</span> │  <span class="hljs-number">5</span> │  <span class="hljs-number">6</span> │  <span class="hljs-number">7</span> │  <span class="hljs-number">8</span> │  <span class="hljs-number">9</span> │ <span class="hljs-number">10</span> │ <span class="hljs-number">11</span> │
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
</code></pre>

<pre class="lang-py s-code-block"><code class="hljs language-python">i= <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>
j= <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">1</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">2</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>    <span class="hljs-number">3</span>    <span class="hljs-number">3</span>
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
│  <span class="hljs-number">0</span> │  <span class="hljs-number">1</span> │  <span class="hljs-number">2</span> │  <span class="hljs-number">3</span> │  <span class="hljs-number">4</span> │  <span class="hljs-number">5</span> │  <span class="hljs-number">6</span> │  <span class="hljs-number">7</span> │  <span class="hljs-number">8</span> │  <span class="hljs-number">9</span> │ <span class="hljs-number">10</span> │ <span class="hljs-number">11</span> │
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
</code></pre>

<pre class="lang-py s-code-block"><code class="hljs language-python">i= <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>    <span class="hljs-number">4</span>    <span class="hljs-number">5</span>    <span class="hljs-number">6</span>    <span class="hljs-number">7</span>    <span class="hljs-number">8</span>    <span class="hljs-number">9</span>   <span class="hljs-number">10</span>   <span class="hljs-number">11</span>
j= <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
│  <span class="hljs-number">0</span> │  <span class="hljs-number">1</span> │  <span class="hljs-number">2</span> │  <span class="hljs-number">3</span> │  <span class="hljs-number">4</span> │  <span class="hljs-number">5</span> │  <span class="hljs-number">6</span> │  <span class="hljs-number">7</span> │  <span class="hljs-number">8</span> │  <span class="hljs-number">9</span> │ <span class="hljs-number">10</span> │ <span class="hljs-number">11</span> │
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
</code></pre>

## Assigning Values

### Assigning Values in ndarrays

    ndarray[location_of_values] = new_value

In [ ]:
a = np.array(['red','blue','black','blue','purple'])
a[0] = 'orange'
print(a)

In [ ]:
ones = np.ones((3,5))


### Assignment Using Boolean Arrays

In [ ]:
a2 = np.array([1, 2, 3, 4, 5])
a2[a2 > 2] = 99

print(a2)

In [ ]:
b = np.linspace(1, 9, num=9, dtype=np.int32)


    bool = array[:, column_for_comparison] == value_for_comparison
    array[bool, column_for_assignment] = new_value

and then all in one line:

    array[array[:, column_for_comparison] == value_for_comparison, column_for_assignment] = new_value

## Adding Rows and Columns to ndarrays

In [ ]:
# primer 2 -1d
ones = np.ones(shape=3)
print(ones)
print(ones.shape)

In [ ]:
# primer 1 -1d
ones = np.ones(3)
print(ones)
print(ones.shape)

In [ ]:
# primer 3 -2d
ones = np.ones(shape=(3,1))
print(ones)
print("----------")
print(ones[0])
print("----------")
print(ones[0,0])
print(ones.shape)

In [ ]:
# primer 4 -2d
ones = np.ones(shape=(1,3))
print(ones)
print("----------")
print(ones[0])
print("----------")
print(ones[0,0])
print(ones.shape)

In [ ]:
# primer 5 -3d
ones = np.ones(shape=(2,3,2))
print(ones)
print("----------")
print(ones[0])
print("----------")
print(ones[0,0])
print(ones.shape)

In [ ]:
ones = np.ones((2, 3))
print(ones)

In [ ]:
zeros = np.zeros(3)
print(zeros)

## Computation on NumPy Arrays: Universal Functions


### The Slowness of Loops



In [ ]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

In [ ]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit -n 1 -r 1 compute_reciprocals(big_array)

### Introducing UFuncs (Universal functions)

[Docs](https://numpy.org/doc/stable/reference/ufuncs.html)



In [ ]:
print(compute_reciprocals(values))
print(1.0 / values)

In [ ]:
%timeit (1.0 / big_array)

## Subarrays as no-copy views

 

In [ ]:
r = np.ones((4,4))
print(r)

In [ ]:
r2 = r[:2,:2]
print(r2)

## Copying Data



In [ ]:
#To avoid this, use r.copy to create a copy that will not affect the original array
r3 = np.random.randint(10, size=(5, 5)) 
print(r3, '\n')

