# Uvod v Numpy

## Datatypes in Python

```C
# Primer C:
int x = 4;
x = "string;
```

In [1]:
# Primer Python:
x = 4
print(type(x), x)

x = "string"
print(type(x), x)

<class 'int'> 4
<class 'str'> string


## Integers in Python

```C
# Python3.4 implementation of long integer
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

![Int in C vs int in py](./images/cint_vs_pyint.png)

## Lists in Python

In [4]:
l = [1, "string", 2.3, False]
print(type(l), l)
datatypes = [type(i) for i in l]
print(datatypes)

<class 'list'> [1, 'string', 2.3, False]
[<class 'int'>, <class 'str'>, <class 'float'>, <class 'bool'>]


![array_vs_list](./images/array_vs_list.png)

In [6]:
l = [0,1,2,3,4,5,6]
print(type(l), l)
print(type(l[0]), l[0])

<class 'list'> [0, 1, 2, 3, 4, 5, 6]
<class 'int'> 0


### Fixed-Type Arrays in Python

In [8]:
import array

L = list(range(10))
A = array.array("i", L)
print(A)

A[0] = 2.3

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


TypeError: 'float' object cannot be interpreted as an integer

# Vectorization

In [9]:
my_numbers = [
    [6,5],
    [1,3],
    [5,6],
    [3,7],
    [1,4],
    [5,8],
    [3,5],
    [8,4]
]

sums = []
for row in my_numbers:
    row_sum = row[0] + row[1]
    sums.append(row_sum)
print(sums)

[11, 4, 11, 10, 5, 13, 8, 12]


![numpy_for_gif](./images/numpy_for.gif)

![numpy_vectorized](./images/numpy_vectorized.gif)

# Numpy Library

[Dokumentacija](http://www.numpy.org/)

```bash
$ pip install numpy
```

In [10]:
import numpy as np

np.__version__

'1.23.5'

## Speed comparison

### %timeit

In [11]:
n = 100_000
sum([1. / i**2 for i in range(1, n)])

1.6449240667982423

In [13]:
%timeit -r 5 -n 30 sum([1. / i**2 for i in range(1, n)])

33 ms ± 956 µs per loop (mean ± std. dev. of 5 runs, 30 loops each)


In [14]:
%%timeit -r 5 -n 30
s = 0.
for i in range(1, n):
    s += 1. / i**2

33.2 ms ± 1.15 ms per loop (mean ± std. dev. of 5 runs, 30 loops each)


In [15]:
import numpy as np
size = 5_000_000

list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

array1 = np.arange(size)
array2 = np.arange(size)

print(list1[:5])
print(array1[:5])

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [18]:
%%timeit -n 10 -r 1
# Python code

sums = []
for el1, el2 in zip(list1, list2):
    sums.append(el1 + el2)
print(sums[:5])

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
616 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)


In [19]:
%%timeit -n 10 -r 1
sums = array1 + array2
print(sums[:5])

[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]
13.7 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 10 loops each)


<hr>

## Ndarray

![1-dimenzional array](./images/one_dim.svg)

<a href="https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array">numpy.array() - documentation</a>

In [26]:
l = [6,1,5,2,3,5,6,4]
ndarray = np.array(l)
print(type(ndarray))
print(ndarray)

<class 'numpy.ndarray'>
[6 1 5 2 3 5 6 4]


In [29]:
print(ndarray[0])
print(ndarray[4])
print(ndarray[-1])

6
3
4


![two dimensional array](./images/Two_Dim.svg)

In [31]:
list_ = [
    [6,5],
    [1,3],
    [2,3],
    [4,3],
    [6,5],
    [2,3]
]

ndarray = np.array(list_)
print(type(ndarray))
print(ndarray)

<class 'numpy.ndarray'>
[[6 5]
 [1 3]
 [2 3]
 [4 3]
 [6 5]
 [2 3]]


---

# Learning through real example

## Importing data

* `pickup_year` - leto vožnje
* `puckup_month` - mesec vožnje. `1` predstavlja Januar, `12` predstavlja December
* `pickup_day` - predstavlja dan v mesecu vožnje
* `pickup_dayofweek` - predstavlja dan v tednu. `1` predstavlja Ponedeljek, `7` predstavlja Soboto
* `pickup_time` - predstavlja čas, ko se je vožnja pričela:
    - `0` - 0:00am-3:59am.
    - `1` - 4:00am-7:59am.
    - `2` - 8:00am-11:59am.
    - `3` - 12:00pm-3:59pm.
    - `4` - 4:00pm-7:59pm.
    - `5` - 8:00pm-11:59pm.
* `pickup_location_code` - predstavlja mesto ali letališče kjer se je vožnja začela
    - `0` - Bronx.
    - `1` - Brooklyn.
    - `2` - JFK Airport.
    - `3` - LaGuardia Airport.
    - `4` - Manhattan.
    - `5` - Newark Airport.
    - `6` - Queens.
    - `7` - Staten Island.
* `dropoff_location_code` - predstavlja meto ali letališle, kjer se je vožnja končala
* `trip_distance` - predstavlja dolžino opravljene poti v miljah
* `trip_length` - predstavlja koliko časa je pot trajala, v sekundah
* `fare_amount` - predstavlja koliko je bila osnovna cena potovanja, v dolarjih
* `fees_amount` - predstavlja koliko dodatnih stroškov je stala vožnja
* `tolls_amount` - predstavlja koliko cestnine se je plačalo za vožnjo
* `tip_amount` - predstavlja koliko napitnine je pustila stranka
* `total_amount` - predstavlja koliko je bila končna cena, katero je plačal potnik. V dolarjih
* `payment_type` - predstavlja način plačila:
    - `1` - Credit card.
    - `2` - Cash.
    - `3` - No charge.
    - `4` - Dispute.
    - `5` - Unknown.
    - `6` - Voided trip.

In [33]:
import csv
import numpy as np

with open("data/nyc_taxis.csv") as f:
    taxi_list = list(csv.reader(f))
    
for row in taxi_list[:5]:
    print(row)

['pickup_year', 'pickup_month', 'pickup_day', 'pickup_dayofweek', 'pickup_time', 'pickup_location_code', 'dropoff_location_code', 'trip_distance', 'trip_length', 'fare_amount', 'fees_amount', 'tolls_amount', 'tip_amount', 'total_amount', 'payment_type']
['2016', '1', '1', '5', '0', '2', '4', '21.00', '2037', '52.00', '0.80', '5.54', '11.65', '69.99', '1']
['2016', '1', '1', '5', '0', '2', '1', '16.29', '1520', '45.00', '1.30', '0.00', '8.00', '54.30', '1']
['2016', '1', '1', '5', '0', '2', '6', '12.70', '1462', '36.50', '1.30', '0.00', '0.00', '37.80', '2']
['2016', '1', '1', '5', '0', '2', '6', '8.70', '1210', '26.00', '1.30', '0.00', '5.46', '32.76', '1']


In [35]:
taxi = taxi_list[1:]
taxi = np.array(taxi, dtype="float")
print(taxi.shape)
print(type(taxi))
for row in taxi[:4]:
    print(row)

(89560, 15)
<class 'numpy.ndarray'>
[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
 2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
 1.000e+00]
[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
 1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
 1.000e+00]
[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
 1.270e+01 1.462e+03 3.650e+01 1.300e+00 0.000e+00 0.000e+00 3.780e+01
 2.000e+00]
[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
 8.700e+00 1.210e+03 2.600e+01 1.300e+00 0.000e+00 5.460e+00 3.276e+01
 1.000e+00]


---

[numpy.genfromtxt](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html)

In [41]:
import numpy as np
taxi = np.genfromtxt("data/nyc_taxis.csv", delimiter=",")
print(taxi.shape)

(89561, 15)


In [42]:
taxi.dtype

dtype('float64')

In [45]:
# taxi = np.genfromtxt("data/nyc_taxis.csv", delimiter=",", dtype="float32")
taxi = np.genfromtxt("data/nyc_taxis.csv", delimiter=",", dtype=np.float64)
print(taxi.dtype)

float64


In [46]:
for row in taxi[:5]:
    print(row)

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
 2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
 1.000e+00]
[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
 1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
 1.000e+00]
[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
 1.270e+01 1.462e+03 3.650e+01 1.300e+00 0.000e+00 0.000e+00 3.780e+01
 2.000e+00]
[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
 8.700e+00 1.210e+03 2.600e+01 1.300e+00 0.000e+00 5.460e+00 3.276e+01
 1.000e+00]


In [47]:
taxi = taxi[1:]
print(taxi[:4])

[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
  1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  1.270e+01 1.462e+03 3.650e+01 1.300e+00 0.000e+00 0.000e+00 3.780e+01
  2.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  8.700e+00 1.210e+03 2.600e+01 1.300e+00 0.000e+00 5.460e+00 3.276e+01
  1.000e+00]]


In [48]:
taxi = np.genfromtxt("data/nyc_taxis.csv", delimiter=",", skip_header=1)
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


---

## Datatypes

<div class="text_cell_render border-box-sizing rendered_html">
<table>
<thead><tr>
<th>Data type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>bool_</code></td>
<td>Boolean (True or False) stored as a byte</td>
</tr>
<tr>
<td><code>int_</code></td>
<td>Default integer type (same as C <code>long</code>; normally either <code>int64</code> or <code>int32</code>)</td>
</tr>
<tr>
<td><code>intc</code></td>
<td>Identical to C <code>int</code> (normally <code>int32</code> or <code>int64</code>)</td>
</tr>
<tr>
<td><code>intp</code></td>
<td>Integer used for indexing (same as C <code>ssize_t</code>; normally either <code>int32</code> or <code>int64</code>)</td>
</tr>
<tr>
<td><code>int8</code></td>
<td>Byte (-128 to 127)</td>
</tr>
<tr>
<td><code>int16</code></td>
<td>Integer (-32768 to 32767)</td>
</tr>
<tr>
<td><code>int32</code></td>
<td>Integer (-2147483648 to 2147483647)</td>
</tr>
<tr>
<td><code>int64</code></td>
<td>Integer (-9223372036854775808 to 9223372036854775807)</td>
</tr>
<tr>
<td><code>uint8</code></td>
<td>Unsigned integer (0 to 255)</td>
</tr>
<tr>
<td><code>uint16</code></td>
<td>Unsigned integer (0 to 65535)</td>
</tr>
<tr>
<td><code>uint32</code></td>
<td>Unsigned integer (0 to 4294967295)</td>
</tr>
<tr>
<td><code>uint64</code></td>
<td>Unsigned integer (0 to 18446744073709551615)</td>
</tr>
<tr>
<td><code>float_</code></td>
<td>Shorthand for <code>float64</code>.</td>
</tr>
<tr>
<td><code>float16</code></td>
<td>Half precision float: sign bit, 5 bits exponent, 10 bits mantissa</td>
</tr>
<tr>
<td><code>float32</code></td>
<td>Single precision float: sign bit, 8 bits exponent, 23 bits mantissa</td>
</tr>
<tr>
<td><code>float64</code></td>
<td>Double precision float: sign bit, 11 bits exponent, 52 bits mantissa</td>
</tr>
<tr>
<td><code>complex_</code></td>
<td>Shorthand for <code>complex128</code>.</td>
</tr>
<tr>
<td><code>complex64</code></td>
<td>Complex number, represented by two 32-bit floats</td>
</tr>
<tr>
<td><code>complex128</code></td>
<td>Complex number, represented by two 64-bit floats</td>
</tr>
</tbody>
</table>

</div>

In [50]:
x = np.array([1,2])
print(x)
print(x.dtype)

x = np.array([1.2, 2.3])
print(x)
print(x.dtype)

[1 2]
int32
[1.2 2.3]
float64


In [52]:
x = np.array([1,2], dtype=np.int8)
print(x)
print(x.dtype)

x = np.array([12,3], dtype=np.float32)
print(x)
print(x.dtype)

[1 2]
int8
[12.  3.]
float32


In [57]:
x = np.array([1,2,128], dtype=np.int8)
print(x.dtype)
print(x)

int8
[   1    2 -128]



---

In [58]:
print(taxi[:4])

[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
  1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  1.270e+01 1.462e+03 3.650e+01 1.300e+00 0.000e+00 0.000e+00 3.780e+01
  2.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  8.700e+00 1.210e+03 2.600e+01 1.300e+00 0.000e+00 5.460e+00 3.276e+01
  1.000e+00]]


In [62]:
np.set_printoptions(precision=2, suppress=True)
print(taxi[:4])

[[2016.      1.      1.      5.      0.      2.      4.     21.   2037.
    52.      0.8     5.54   11.65   69.99    1.  ]
 [2016.      1.      1.      5.      0.      2.      1.     16.29 1520.
    45.      1.3     0.      8.     54.3     1.  ]
 [2016.      1.      1.      5.      0.      2.      6.     12.7  1462.
    36.5     1.3     0.      0.     37.8     2.  ]
 [2016.      1.      1.      5.      0.      2.      6.      8.7  1210.
    26.      1.3     0.      5.46   32.76    1.  ]]


---

## Ndarray shape

In [63]:
print(taxi)

[[2016.      1.      1.   ...   11.65   69.99    1.  ]
 [2016.      1.      1.   ...    8.     54.3     1.  ]
 [2016.      1.      1.   ...    0.     37.8     2.  ]
 ...
 [2016.      6.     30.   ...    5.     63.34    1.  ]
 [2016.      6.     30.   ...    8.95   44.75    1.  ]
 [2016.      6.     30.   ...    0.     54.84    2.  ]]


In [64]:
data = [[1, 2, 3],
       [50, 100, 150]]

ndarray = np.array(data)
print(ndarray.shape)

(2, 3)


In [65]:
print(taxi.shape)

(89560, 15)


In [66]:
ndarray = np.array(data)
print(ndarray.shape)

(2, 3)


In [67]:
ndarray.size

6

In [68]:
ndarray.ndim

2

## Selecting elements and Slicing

![slicing](./images/selection_rows.svg)

In [70]:
data = [[5,2,8,1,8],
       [9,6,4,0,1],
       [9,5,2,4,4],
       [5,0,8,5,5],
       [2,4,7,1,7]]
ndarray = np.array(data)
print(ndarray)

[[5 2 8 1 8]
 [9 6 4 0 1]
 [9 5 2 4 4]
 [5 0 8 5 5]
 [2 4 7 1 7]]


In [72]:
print(data[2])
print(ndarray[2])

[9, 5, 2, 4, 4]
[9 5 2 4 4]


In [73]:
print(data[2:])
print(ndarray[2:])

[[9, 5, 2, 4, 4], [5, 0, 8, 5, 5], [2, 4, 7, 1, 7]]
[[9 5 2 4 4]
 [5 0 8 5 5]
 [2 4 7 1 7]]


In [74]:
print(data[1][4])
print(ndarray[1][4])

1
1


In [75]:
print(data[1][2:])
print(ndarray[1][2:])

[4, 0, 1]
[4 0 1]



```python
ndarray[row_index , column_index]
```

In [79]:
print(ndarray)

second_row = ndarray[1]
print(second_row)

print(ndarray[1][4])
print(ndarray[1, 4])

[[5 2 8 1 8]
 [9 6 4 0 1]
 [9 5 2 4 4]
 [5 0 8 5 5]
 [2 4 7 1 7]]
[9 6 4 0 1]
1
1


In [81]:
print(ndarray)
print()
print(ndarray[:, 3])

[[5 2 8 1 8]
 [9 6 4 0 1]
 [9 5 2 4 4]
 [5 0 8 5 5]
 [2 4 7 1 7]]

[1 0 4 5 1]


In [86]:
print(ndarray[1:4, 2:4])

[[4 0]
 [2 4]
 [8 5]]


In [87]:
print(ndarray)
print()

print(ndarray[[1,3,4], 2])

[[5 2 8 1 8]
 [9 6 4 0 1]
 [9 5 2 4 4]
 [5 0 8 5 5]
 [2 4 7 1 7]]

[4 8 7]


In [88]:
print(ndarray)

print(ndarray[[False, True, False, False, True], 2:])

[[5 2 8 1 8]
 [9 6 4 0 1]
 [9 5 2 4 4]
 [5 0 8 5 5]
 [2 4 7 1 7]]
[[4 0 1]
 [7 1 7]]


## Vectorized Operations

In [89]:
ndarray1 = np.array([6,1,5,2,3,5])
ndarray2 = np.array([5,7,6,3,8,7])

data = ndarray1 + ndarray2
print(data)

[11  8 11  5 11 12]


In [90]:
data = ndarray1 - ndarray2
print(data)

[ 1 -6 -1 -1 -5 -2]


In [91]:
data = ndarray1 * ndarray2
print(data)

[30  7 30  6 24 35]


In [92]:
data = ndarray1 / ndarray2
print(data)

[1.2  0.14 0.83 0.67 0.38 0.71]


In [93]:
ndarray1 = np.array([1,2,3])
ndarray2 = np.array([1,2,3,4])

data = ndarray1 + ndarray2
print(data)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [94]:
ndarray1 = np.array([6,1,5,2,3,5])
ndarray2 = np.array([5,7,6,3,8,7])

data = np.add(ndarray1, ndarray2)
print(data)

[11  8 11  5 11 12]


In [95]:
trip_distance = taxi[:, 7]
print(trip_distance)

[21.   16.29 12.7  ... 17.48 12.76 17.54]


In [97]:
trips_length_seconds = taxi[:, 8]
trips_length_hours = trips_length_seconds / (60 *60)

In [101]:
trips_mph = trip_distance / trips_length_hours
trips_mph

array([37.11, 38.58, 31.27, ..., 22.3 , 42.42, 36.9 ])

---

## Calculating Statistics

[ndarray.min()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html)

<ul>
<li><a target="_blank" href="https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.min.html#numpy.ndarray.min"><code>ndarray.min()</code> izračun minimalne vrednosti</a></li>
<li><a target="_blank" href="https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.ndarray.max.html"><code>ndarray.max()</code> izračun maximalne vrednosti</a></li>
<li><a target="_blank" href="https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.mean.html#numpy.ndarray.mean"><code>ndarray.mean()</code> izračun povprečne vrednosti</a></li>
<li><a target="_blank" href="https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.sum.html#numpy.ndarray.sum"><code>ndarray.sum()</code> izračun sum vrednosti</a></li>
</ul>

![](./images/array_method_axis_none.svg)

![](./images/array_method_axis_1.svg)

![](./images/array_method_axis_0.svg)

![](./images/axis_param.svg)

---

# Boolean Indexing

## Boolean Arrays

## Boolean Indexing

## Boolean Indexing 2D ndarrays

---

----

---

# Changing Values

## Ndarray copy

---

# Changing ndarrays

## Extending rows and columns

[numpy.concatenate()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)

[numpy.reshape()](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

## How shapes are handeled

<pre class="lang-py s-code-block"><code class="hljs language-python">┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
│  <span class="hljs-number">0</span> │  <span class="hljs-number">1</span> │  <span class="hljs-number">2</span> │  <span class="hljs-number">3</span> │  <span class="hljs-number">4</span> │  <span class="hljs-number">5</span> │  <span class="hljs-number">6</span> │  <span class="hljs-number">7</span> │  <span class="hljs-number">8</span> │  <span class="hljs-number">9</span> │ <span class="hljs-number">10</span> │ <span class="hljs-number">11</span> │
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
</code></pre>

<pre class="lang-py s-code-block"><code class="hljs language-python">i= <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>    <span class="hljs-number">4</span>    <span class="hljs-number">5</span>    <span class="hljs-number">6</span>    <span class="hljs-number">7</span>    <span class="hljs-number">8</span>    <span class="hljs-number">9</span>   <span class="hljs-number">10</span>   <span class="hljs-number">11</span>
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
│  <span class="hljs-number">0</span> │  <span class="hljs-number">1</span> │  <span class="hljs-number">2</span> │  <span class="hljs-number">3</span> │  <span class="hljs-number">4</span> │  <span class="hljs-number">5</span> │  <span class="hljs-number">6</span> │  <span class="hljs-number">7</span> │  <span class="hljs-number">8</span> │  <span class="hljs-number">9</span> │ <span class="hljs-number">10</span> │ <span class="hljs-number">11</span> │
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
</code></pre>

<pre class="lang-py s-code-block"><code class="hljs language-python">i= <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">1</span>    <span class="hljs-number">1</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">2</span>    <span class="hljs-number">2</span>    <span class="hljs-number">2</span>
j= <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>    <span class="hljs-number">0</span>    <span class="hljs-number">1</span>    <span class="hljs-number">2</span>    <span class="hljs-number">3</span>
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
│  <span class="hljs-number">0</span> │  <span class="hljs-number">1</span> │  <span class="hljs-number">2</span> │  <span class="hljs-number">3</span> │  <span class="hljs-number">4</span> │  <span class="hljs-number">5</span> │  <span class="hljs-number">6</span> │  <span class="hljs-number">7</span> │  <span class="hljs-number">8</span> │  <span class="hljs-number">9</span> │ <span class="hljs-number">10</span> │ <span class="hljs-number">11</span> │
└────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
</code></pre>

---

---

---